### ISSUE TITLE
(Story: #11) Repository BMicro; Set up automizations

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#1]

**Comment by paulmueller** [comment]
FYI: To test the automation, I have to make PRs to the `main` branch, breaking our current workflow.

**Comment by paulmueller** [comment]
I would like to apologize for starting with a comparatively high version number "0.1.0". It was a typo, I wanted to write "0.0.1". But since it is now already on PyPI, there is no way back.

**Comment by matthias-baer** [comment]
Ok, then we will rebase after you are done

Von: Paul Müller <notifications@github.com>
Antworten an: BrillouinMicroscopy/BMicro <reply@reply.github.com>
Datum: Freitag, 15. Januar 2021 um 15:22
An: BrillouinMicroscopy/BMicro <BMicro@noreply.github.com>
Cc: "Bär, Matthias" <matthias.baer@mpl.mpg.de>, Assign <assign@noreply.github.com>
Betreff: Re: [BrillouinMicroscopy/BMicro] Repository BMicro; Set up automizations (#1)


FYI: To test the automation, I have to make PRs to the main branch, breaking our current workflow.

**Comment by paulmueller** [comment]
readthedocs, pypi, and GitHub actions are working and merged back to 1-smoke-test. The only thing missing is automatic building of installers for macOS and Windows. I will proceed with those as soon as #3 is done.

**Comment by paulmueller** [comment]
Everything is in place now.
