### ISSUE TITLE
Userstory: Load File in Data View

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#11]
branch: 11-load-file

As a user of BMicro, I want to load measurement data from a HDF5 file so that I can evaluate that data later.

Details:
The user shall be able to select the hdf5 file from an "open file dialog" triggered by a file menu. When the (single) file is selected, the application shall show information of the file as displayed in the "file" group of the screenshot below. The combobox "repetition" shall allow to select any of the available measurement series in the file. The data view is read-only. The comment shown in the screen shot is not editable. The window should be resizable.

Acceptance criteria:

- Requirements fulfilled as described above
- Test coverage > 90%, both in BMicro and bmlab; coding conventions fulfilled (flake8 passes)
- Code is documented
- Changes are finally merged to main branches; deployment to PyPi not necessary (?)

<img width="635" alt="image" src="https://user-images.githubusercontent.com/67058107/105376512-1fed3600-5c0a-11eb-99f6-b427da3fe552.png">

**Comment by matthias-baer** [comment]
I presume that resolution x, y, z is the attribute with the same name in the HDF file for the group 'Brillouin/0/payload', right?

**Comment by matthias-baer** [comment]
@raimund-schluessler I presume that Calibration = true means that there is a calibration group under Brillouin/0/ for repetition 0?

**Comment by matthias-baer** [comment]
@raimund-schluessler Where in the HDF file is "Comment" stored?

**Comment by raimund-schluessler** [comment]
> 
> 
> @raimund-schluessler I presume that resolution x, y, z is the attribute with the same name in the HDF file for the group 'Brillouin/0/payload', right?

Yes, correct.

**Comment by raimund-schluessler** [comment]
> 
> 
> @raimund-schluessler I presume that Calibration = true means that there is a calibration group under Brillouin/0/ for repetition 0?

Unfortunately not. This group is always present. Only if datasets are available under calibration/data then it is true.

**Comment by raimund-schluessler** [comment]
> 
> 
> @raimund-schluessler Where in the HDF file is "Comment" stored?

It's an attribute on the root level of the file, named `comment`. But I think we can omit it, since it is not used at the moment and always reads "Brillouin data".
