### ISSUE TITLE
error even the file can be loaded

### ISSUE THREAD

**Issue by juko1** [BrillouinMicroscopy/BMicro#113]
<img width="970" alt="Screen Shot 2022-02-15 at 13 56 24" src="https://user-images.githubusercontent.com/99735151/154066490-ab28f3c1-8a8a-4987-b2ed-25d93b0cc896.png">
<img width="967" alt="Screen Shot 2022-02-15 at 13 56 32" src="https://user-images.githubusercontent.com/99735151/154066513-bdf89224-a676-43e8-97f0-e1c86336db85.png">

**Comment by raimund-schluessler** [comment]
In my case this happens sometimes if the file I try to open is located on a network drive (so it might take longer to open). The evaluation works fine nevertheless.
It never happens with a file locally on the PC.

**Comment by raimund-schluessler** [comment]
I don't see this behaviour with 0.1.5. anymore. @juko1 Could you please test if this still happens for you with the latest release?

**Comment by raimund-schluessler** [comment]
I can't reproduce this anymore. Please reopen if this still occurs for you.
