### ISSUE TITLE
BMicro shuts down after clicking evaluate

### ISSUE THREAD

**Issue by juko1** [BrillouinMicroscopy/BMicro#139]
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 11 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by raimund-schluessler** [comment]
Thanks. Is this the complete warning/error message? I have never seen it honestly.
But as this again is an issue with multiprocessing, see #140, I tend to disable multiprocessing alltogether until we can handle it properly. This will slowdown the evaluation a bit (I think it was factor 2), but at least makes the program usable again (I hope).
@paulmueller Feedback is very welcome inn case you have an idea or more experience with multiprocessing.

**Comment by juko1** [comment]
I've got a problem report for Python as well. I'll send you that via email, because it's too long for this comment window.

**Comment by paulmueller** [comment]
Sorry, that's too technical for me. Maybe you can find something on stackoverflow? Have tried upgrading PyInstaller?

**Comment by raimund-schluessler** [comment]
> Sorry, that's too technical for me. Maybe you can find something on stackoverflow? Have tried upgrading PyInstaller?

PyInstaller is the latest version already. These multiprocessing errors seem a bit obscure and difficult to solve. I will check further, but disable multiprocessing for now.

**Comment by raimund-schluessler** [comment]
Closed by https://github.com/BrillouinMicroscopy/bmlab/pull/81
