### ISSUE TITLE
DMG opens windows in infinite loop

### ISSUE THREAD

**Issue by raimund-schluessler** [BrillouinMicroscopy/BMicro#140]
This is likely an issue of multiprocessing combined with how pyinstaller packes the program into a DMG.

**Comment by juko1** [comment]
Another bug: BMicro shuts down when it cannot find the peaks for all calibrations (Extraction mode). Selecting the peaks separately works.

**Comment by raimund-schluessler** [comment]
> Another bug: BMicro shuts down when it cannot find the peaks for all calibrations (Extraction mode). Selecting the peaks separately works.

Please open a separate ticket for this and explain how to reproduce this. If you could upload the source and session file leading to the error, this would also help. Thanks!

**Comment by raimund-schluessler** [comment]
Seems to be still not fixed even without multiprocessing.
