### ISSUE TITLE
Prepare widget for the Peak Selection Tab

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#16]
Create a ui-file with Qt Designer / Creator for the widget containing the content of the "Peak Selection" tab. As a guideline, see the screen shot below. User whatever WIP branch is currently active.

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/67058107/105383275-3a76dd80-5c11-11eb-9a61-39a8ff8bdf01.png">

**Comment by raimund-schluessler** [comment]
This is implemented.
