### ISSUE TITLE
(Story #11 and #13) BMicro: Complete the data tab ui-file

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#19]
**Complete** datatab view, including preview.

So far only the left hand side is contained in the UI-file.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/67058107/106563246-cc44eb80-652b-11eb-8889-ef660c29c77e.png">

**Comment by matthias-baer** [comment]
Maybe someone can have a look at the UI file. I'm not used to the designer and I'm not sure how to apply autosize constraints.

**Comment by raimund-schluessler** [comment]
> 
> 
> Maybe someone can have a look at the UI file. I'm not used to the designer and I'm not sure how to apply autosize constraints.

I will have a look.

**Comment by matthias-baer** [comment]
> > Maybe someone can have a look at the UI file. I'm not used to the designer and I'm not sure how to apply autosize constraints.
> 
> I will have a look.

Thanks, but never mind. I found out how to do it. :-)

**Comment by raimund-schluessler** [comment]
> 
> 
> > > Maybe someone can have a look at the UI file. I'm not used to the designer and I'm not sure how to apply autosize constraints.
> > 
> > 
> > I will have a look.
> 
> Thanks, but never mind. I found out how to do it. :-)

Ok, great. Sorry I hadn't had the time to do it.

**Comment by raimund-schluessler** [comment]
@matthias-baer Should we close this issue now that it's in Done?

**Comment by matthias-baer** [comment]
I think so.
