### ISSUE TITLE
(Story #11) Provide small test file with ~3-4 images

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#24]

**Comment by matthias-baer** [comment]
@raimund-schluessler For testing purpose, it would be good to have a file with 2 repetitions and a few images for each repetition.

**Comment by Tianbe** [comment]
Ah sorry I thought we would have that file

**Comment by raimund-schluessler** [comment]
Added the file in 0e3c04e5e6e3e27599276eb742472f33a1487652
