### ISSUE TITLE
User Story: Extraction tab with basic functionality 

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#27]
Dev-Branch: 27-basic-extraction

On the "Extraction" tab, I want to select peak positions for each calibration dataset in the opened file. 

The user shall select the calibration dataset from the top left combo box. Upon selection of the calibration dataset, the image shows the corresponding data. Then click the "Select button" and mark the four relevant peaks in the image. The selected points (and the circle fit through the points) are plotted as an overlay over the image.

From a UI perspective, for now only implement:

- The calibration selection combobox
- The select, optimize and clear button
- The image view plus marked points
- The fit through the marked points

**Comment by matthias-baer** [comment]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/67058107/106759072-950d3200-6632-11eb-9c65-e3f13cc6b13c.png">

**Comment by raimund-schluessler** [comment]
I think this is done, right?

**Comment by matthias-baer** [comment]
Yes, I think so.
