### ISSUE TITLE
User Story: Calibration tab with basic functionality

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#35]
Dev-Branch: 35-basic-calibration

On the "Calibration" tab, I want to select the Brillouin and Rayleigh peaks of the spectrum and fit Lorentz functions to determin the frequency scale. I want to do this for each calibration image.

The user shall select the calibration dataset from the top left combo box. Upon selection of the calibration dataset, the plot shows the image data along the circle fitted in the extraction tab. The horizontal axis is shown in units of pixels first.

When the user clicks on "Select" Brillouin peaks, the user shall be able to select the ranges with the Brillouin peaks in the plot.  When done, the user clicks "Done" (same button as "Select"). The selected ranges are shown in the plot.

The same applies to selecting the Rayleigh peaks.

When the user clicks on "Calibrate", the data ranges of are fitted to Lorentz functions. When done, the fitted peak positions are shown in the plot. When the fitting is done, the frequency axis is determined and the plot now shows the spectrum in terms of frequency instead of pixels.

When the user clicks "Clear", the fit is removed and the plot is reset.

For this user story, only the basic functionality is needed. In terms of UI, this means:

- combobox for calibration data selection
- "Clear", "Select" buttons for Brillouin and Rayleigh peaks
- Buttons "Clear" and "Calibrate"
- The plot

**Comment by matthias-baer** [comment]
<img width="817" alt="image" src="https://user-images.githubusercontent.com/67058107/107784766-2162d780-6d4c-11eb-8262-25f6aac97c26.png">

**Comment by raimund-schluessler** [comment]
This is done. Next one is https://github.com/BrillouinMicroscopy/BMicro/issues/55
