### ISSUE TITLE
(User Story #35) Show extracted spectrum for selected calibration dataset

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#36]
Extract the data from a given calibration image along a circle specified by selected points in the extraction tab:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/67058107/108864327-61e70e80-75f2-11eb-9973-e8b93664a94c.png">

The data shall be extracted at equidistant points along the circle by taking rectangles perpendicular to the points on the circle. Take the sum (simple? weighted? other than sum?  of each rectangle to represent the data point. Plot all extracted points as a line plot in the calibration tab.

**Comment by matthias-baer** [comment]
@raimund-schluessler I changed the implementation for the extraction from non-interpolating rectangles to interpolating lines:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/67058107/109509277-0230ad80-7aa1-11eb-9d85-624cb29ac471.png">

The extracted spectrum for one frame of one calibration image (no averaging over frame is ok?) looks like this:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/67058107/109509408-255b5d00-7aa1-11eb-9bcc-3d6c31c98d58.png">

Does that look plausible to you?

**Comment by raimund-schluessler** [comment]
@matthias-baer Thanks a lot, this looks good. Averaging over multiple images is not necessary. We will fit the spectrum separately for each image.
