### ISSUE TITLE
(User Story #35) Select spectral ranges for Brillouin and Rayleigh peaks

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#37]
From the given circular slice of the calibration data, the user shall be able to select different regions which belong to the Brillouin and Rayleigh peaks. Use the LassoSelector tool of matplotlib to do that.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/67058107/108885810-86e67c00-7608-11eb-95ed-f5571b9468ae.png">

**Comment by matthias-baer** [comment]
When selecting spectral ranges in the Matlab version, do you select each Brillouin peak separately or do you select one Brillouin region as double peak?

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler When selecting spectral ranges in the Matlab version, do you select each Brillouin peak separately or do you select one Brillouin region as double peak?

We select the whole region including both Brillouin peaks (for water and methanol). You also have to fit a double-Lorentz peak instead of two single Lorentz peaks. Since the peaks overlap, fitting two separate peaks would bias the fit towards the other peak, respectively.

**Comment by matthias-baer** [comment]
That's why I'm asking. Fitting each peak individually would be quite unstable.
