### ISSUE TITLE
Closing a file should reset all tabs

### ISSUE THREAD

**Issue by raimund-schluessler** [BrillouinMicroscopy/BMicro#43]
The data in the calibration tab is currently not reset when closing a file. It is still possible to select different calibration from the now closed file, leading to a program crash.

**Comment by matthias-baer** [comment]
Fixed clearing the extraction tab. But I not see that the orientation controls on the data tab should probably (?) also be reset to the default values.

**Comment by matthias-baer** [comment]
Closed with commit 5dd08f2

**Comment by raimund-schluessler** [comment]
> But I not see that the orientation controls on the data tab should probably (?) also be reset to the default values.

I don't have a strong opinion here. I am fine with the current behaviour, as long as the user cannot make the app exit unexpectedly.
