### ISSUE TITLE
Allow to adjust extraction granularity

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#44]
Currently, on the extraction tab, the granularity (spacing of discretization and area of extraction patches)

<img width="388" alt="image" src="https://user-images.githubusercontent.com/67058107/109113755-09705800-773d-11eb-97b0-dbfbf4210c25.png">

is hard wired:

```
phis = discretize_arc(circle, img.shape, num_points=200)

width = 2
length = 7

self._plot_extraction_patches(circle, phis, length, width)

values = self._extract_values(
    image_key, circle, phis, length, width)
session.extraction_model().set_extracted_values(
    image_key, phis, values)
```

Include controls in the UI to enable the user to use different settings for that.

**Comment by raimund-schluessler** [comment]
Not sure this is necessary. In the Matlab version, it is possible to adjust these values, but we basically never use that option. So I think default values would be fine (at least for now).

But what needs to be checked, is that the same values as in the Matlab version are used.

**Comment by matthias-baer** [comment]
Yes, that's probably not the case yet. Also, I may have implemented a different approach for extraction, so let's discuss that tomorrow.

**Comment by Tianbe** [comment]
Did we now decide to implement this? If yes I could work on that

**Comment by Tianbe** [comment]
Is the given example code actually still there? Could not find this piece

**Comment by raimund-schluessler** [comment]
> 
> 
> Is the given example code actually still there? Could not find this piece

Probably not. Give me some minutes, I currently work on the code you would need to adjust. However, I am not sure this function is critical at the moment.

**Comment by raimund-schluessler** [comment]
The width of the extraction arc is set here https://github.com/BrillouinMicroscopy/bmlab/blob/35-basic-calibration/bmlab/models/extraction_model.py#L89-L90.

But before you implement a GUI for changing the value, I would propose to make BMicro actually showing the extraction positions from bmlab. At the moment, the extraction positions shown in BMicro do not respect settings in bmlab but are calculated in BMicro as seen here:

https://github.com/BrillouinMicroscopy/BMicro/blob/35-basic-calibration/bmicro/gui/extraction/extraction_view.py#L158-L168

**Comment by raimund-schluessler** [comment]
> But before you implement a GUI for changing the value, I would propose to make BMicro actually showing the extraction positions from bmlab. At the moment, the extraction positions shown in BMicro do not respect settings in bmlab but are calculated in BMicro as seen here:
> 
> https://github.com/BrillouinMicroscopy/BMicro/blob/35-basic-calibration/bmicro/gui/extraction/extraction_view.py#L158-L168

Done in 76e8f2c67009fb39662d4375e6d856b14d9bd76f
