### ISSUE TITLE
(User Story #35) Merge overlapping regions when selecting spectral ranges.

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#45]
Currently, when selecting spectral ranges in the calibration tab, selecting two overlapping regions counts as two separate regions. Instead, when two regions overlap, they should be merged into one region.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/67058107/109119697-5526ff80-7745-11eb-869f-d055bb52af08.png">

**Comment by Tianbe** [comment]
I wonder if this is actually necessary and also useful. If I for example accidentally overlap the region of the Brillouin peaks with the Rayleigh peaks, why should I merge these regions? Then I would end up with a mixed Brillouin-Rayleigh region...

**Comment by raimund-schluessler** [comment]
> I wonder if this is actually necessary and also useful. If I for example accidentally overlap the region of the Brillouin peaks with the Rayleigh peaks, why should I merge these regions? Then I would end up with a mixed Brillouin-Rayleigh region...

Merging overlapping Brillouin and Rayleigh regions doesn't make sense. But merging overlapping Brillouin (or Rayleigh) regions is fine.

**Comment by Tianbe** [comment]
So in case I would like would like to extend the selected region. Then I would not have to clear the selection again. So I guess that boils down to adjusting CalibrationModel.add_brillouin_region() and check for overlaps, before the new region is appended to the brillouin_regions. I guess i could take care of that

**Comment by raimund-schluessler** [comment]
Implemented with https://github.com/BrillouinMicroscopy/bmlab/commit/83b35bb6638ad6750c10cdfd2a285cf174d8fb32
