### ISSUE TITLE
BMicro is blocking builds for my other projects on Appveyor

### ISSUE THREAD

**Issue by paulmueller** [BrillouinMicroscopy/BMicro#46]
Hey there,

the BMicro Appveyor build is connected to my account. The problem is that there is only one concurrent build per account and this blocks my other builds, especially because now the build won't finish because of a pyinstaller-issue (which I have no time to debug right now).

Would someone of you @raimund-schluessler ? @matthias-baer ? be willing to connect your GitHub account to Appveyor? There is nothing much to do. I believe once I cut my connection to the BrillouinMicroscopy organization and you add it. I should be fine...

Thanks!

**Comment by raimund-schluessler** [comment]
I am fine with doing so, but could you give me a hint on how to?

**Comment by paulmueller** [comment]
Basic setup:

1. Go to https://ci.appveyor.com and login with your GitHub account (you have to give them access to your public repositories)
2. Allow Appveyor access to the BrillouinMicroscopy organization and add a new project BMicro

Setting up GitHub releases:

1. Go to https://github.com/settings/tokens and create a new token. Name it "deployment to releases with appveyor". Only check "public_repo" permissions.
2. Copy the token, go to https://ci.appveyor.com/tools/encrypt and encrypt it. Replace my token with yours in the .appveyor file: https://github.com/BrillouinMicroscopy/BMicro/blob/main/.appveyor.yml#L76

**Comment by raimund-schluessler** [comment]
Done. I pushed it to the 27-basic-extraction branch. Should I also commit to the main branch?

**Comment by paulmueller** [comment]
Thanks! No need for editing master. Could you please post the project link? I will update the badge.

**Comment by raimund-schluessler** [comment]
I guess it should be https://ci.appveyor.com/project/raimund-schluessler/BMicro
