### ISSUE TITLE
Lorentz fit is unstable

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#50]
The current implementation of the Lorentz fit is not stable. In particular for data from actual images, the fit fails now. The data extracted and to be fitted looks like this:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/67058107/114358573-57b5ab00-9b73-11eb-86d0-828fbb7c266a.png">

I have implemented a test that shows the failing of the fit (in `bmlab/tests/test_fits.py`)

```
def _test_fit_spectral_range():
    """ The data for this test case has been extracted manually from the running
        BMicro application.
    """

    data_dir = pathlib.Path(__file__).parent / 'data'

    region = np.load(data_dir / 'rayleigh_reg0_region.npy')
    xdata = np.load(data_dir / 'rayleigh_reg0_xdata.npy')
    ydata = np.load(data_dir / 'rayleigh_reg0_ydata.npy')

    fit_lorentz(xdata[range(*region)], ydata[range(*region)])

    # import matplotlib.pyplot as plt
    # plt.plot(xdata[range(*region)], ydata[range(*region)])
    # plt.show()
```

**Comment by raimund-schluessler** [comment]
I think I fixed this on Friday, but forgot to push. 🙈 Let me merge my changes with your test and check if this fixes it.

**Comment by matthias-baer** [comment]
Ah, great. Then you now have an additional test case that comes from a real microscopy file. :-)

**Comment by raimund-schluessler** [comment]
I pushed my changes. Could you check again, the test doesn't seem to run automatically.

**Comment by matthias-baer** [comment]
Yes, because I commented it out by the leading underscore.

**Comment by raimund-schluessler** [comment]
Could it be that the data file is missing from your commit? The test seems to fail loading the data as far as I can tell.

**Comment by matthias-baer** [comment]
RIght, I forgot to add it. 🙈

**Comment by matthias-baer** [comment]
Ok, pushed and test is running.
