### ISSUE TITLE
Translate pixel axis into frequency axis on calibration tab.

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#52]
Currently the calibration tab shows the spectrum in terms of pixes:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/67058107/114507829-f7d30900-9c33-11eb-90f0-65c89251e006.png">

 Once the peaks are fitted, the pixel axis can be translated into a frequency axis.

**Comment by raimund-schluessler** [comment]
I planned to implement this today.

**Comment by raimund-schluessler** [comment]
Done.
