### ISSUE TITLE
Provide example script for headless evaluation

### ISSUE THREAD

**Issue by raimund-schluessler** [BrillouinMicroscopy/BMicro#61]
This will also serve as a test case to check that all relevant functions are available in bmlab.

As long as #58 and #59 are not implemented, the necessary points and regions will have to be added manually.

**Comment by matthias-baer** [comment]
Hm.... I already did that but I forgot to push it.. :-)

**Comment by matthias-baer** [comment]
And it needs to be updated, because that's from the time without controllers.

**Comment by raimund-schluessler** [comment]
Closed with https://github.com/BrillouinMicroscopy/bmlab/pull/19.

We should encapsulate bmlab a bit better, because evaluating a file should not require internal knowledge of bmlab as it is necessary here:
https://github.com/BrillouinMicroscopy/bmlab/blob/main/tests/test_run_bmlab_pipeline.py#L52-L65

But that is for a different PR.
