### ISSUE TITLE
BMicro crashes when selecting different tab while evaluating

### ISSUE THREAD

**Issue by raimund-schluessler** [BrillouinMicroscopy/BMicro#62]

**Comment by maroba** [comment]
I will probably have some time this afternoon for looking into the current issues...

**Comment by matthias-baer** [comment]
I will probably have some time this afternoon to look into the current issues...

**Comment by raimund-schluessler** [comment]
> 
> 
> I will probably have some time this afternoon to look into the current issues...

Great. I will likely merge the 35-basic-calibration branch today, since the most important features are present (although sometimes a bit buggy still). So I think it makes sense to then create a branch per issue that is being worked on.

**Comment by raimund-schluessler** [comment]
The problem is that the whole UI is recreated when selecting a different tab. This also resets the repetition combobox which leads to the `_current_repetition_key` being an empty string (as long as the UI is updated). Hence https://github.com/BrillouinMicroscopy/bmlab/blob/main/bmlab/session.py#L40-L44 returns `None` and the calibration aborts.

The whole UI being reset and recreated is probably also the reason why it takes so long to switch between tabs.
