### ISSUE TITLE
Create app icon

### ISSUE THREAD

**Issue by matthias-baer** [BrillouinMicroscopy/BMicro#9]
When the app is running, it shall show a unique app icon instead of the standard Python rocket. Create the icon with appropriate dimensions and integrate it in the application. Use whatever user story branch is currently alife.

**Comment by matthias-baer** [comment]
Not sure about the required dimensions of app icon.... maybe someone can look this up.

**Comment by paulmueller** [comment]
We should start with an SVG file (preferably created with inkscape, because it's OSS). For Windows we need an .ico file. For macOS we need an .icns file. These contain the icon at different resolutions (Up to 256px width I think).

**Comment by paulmueller** [comment]
I created a preliminary icon and used it in #1.
